### ISSUE TITLE
MnemonicPassPhrase.createFromEntropy() generate 12 words mnemonic

### ISSUE THREAD

**Issue by domakun** [nemtech/symbol-hd-wallets#14]
MnemonicPassPhrase.createFromEntropy generate 12 words mnemonics while MnemonicPassPhrase.createRandom() generate 24 words mnemonics

**Comment by rg911** [comment]
@domakun does this issue still exist?

**Comment by domakun** [comment]
> @domakun does this issue still exist?

sorry, I will close it soon
